Ipv6: false #是否使用IPv6, 注意所有客户端需要配重一直
FanOut: 2  # 每个节点的扇出是多少
LocalAddress: "127.0.0.1" #启动后会自动把这个字段填充端口
Coloring: true  #是否开启染色算法
Test: true  #测试模式下 membership list里的ip不会被删除。并且会发送额外的信息到固定的服务端进行调试

SyncSend: true #现在都是异步的，也就是说为了避免乱序是要进行复制。待开发，消息可以分为同步和异步进行发送，小的消息用异步，大的消息用同步